### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by KevinGimbel** [kevingimbel/vhost.go#1]
TODO for a proper release that could compete with the [Bash version](https://github.com/kevingimbel/vhost):

Functionality:
- [x] Create .conf file in Output Directory
- [ ] Create log directory
- [ ] Append entry to `/etc/hosts/` files
- [ ] Reload Apache Server

Building `vhost-cli`: 
- [ ] Create binary builds for common systems under releases
- [ ] Write proper documentation about building from source with `go build`

Other: 
- [ ] Provide example about using vhost inside another script (other than `vhost-cli`)
